 
// let person = "John Doe", section ="hi";
// console.log(person,section);

//operators

//Assignment operators
let _x = 10;
console.log(_x);

//---Addition
let x = 5 + 2 + 3;
console.log(x);

let y ="5" + 3; //combined
console.log(y);

let z = 6 + "6" + 9;
console.log(z);

//---Subtraction
let __x=20-5-"5";
console.log(__x);
 
//---multiplication
let __y = 8*8*"8";
console.log(__y);

//--exponentiation
let __z = 4 ** 2 ** "2";
console.log(__z);

//division
let __w = 100 / 5 / "2";
console.log(__w);

//modulus
let __v = 29 % "2";
console.log(__v);

//increment
let a = 5;
console.log(++a);

//decrement
let u = "7"; 
console.log(--u);

//assignment operators
let v = 20;
v += 5;
console.log(v);

let w=20;
w -=5;
console.log(w);

let h=20;
h *=5;
console.log(h);

let r=20;
r**=5;
console.log(r);

let t=20;
t /=5;
console.log(t);

let q=20;
q !=5;
console.log(q);

//comparison operators
console.log(5==5);
console.log(5!=5);
console.log(5<=5);
console.log(5==5);